import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Tea Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>TEA-COMMERCE</h1>
      <h3>Balance and harmony for body and mind</h3>
      
      <div className={styles.btn_shopping}>
        <Link href="/teas"> Go Tea Shopping </Link>
      </div>
    </div>
  );
}
